/**
 * Pairs rendering functionality for the Coffee Roulette application.
 * Handles the display of generated pairs in the UI.
 *
 * @fileoverview This module provides functionality to render participant pairs
 * generated by the pairing algorithm in a user-friendly list format.
 */

/**
 * Renders the generated pairs in the UI as a Bootstrap list group.
 * Each pair is displayed as a list item with participants separated by " & ".
 *
 * @param {string[][]} pairs - Array of pairs, where each pair is an array of participant emails
 * @param {string[]} pairs[] - Individual pair containing participant email addresses
 *
 * @example
 * // Render pairs for current round
 * renderPairs([
 *   ['john@example.com', 'jane@example.com'],
 *   ['bob@example.com', 'alice@example.com']
 * ]);
 *
 * @example
 * // Handle empty pairs array
 * renderPairs([]); // Clears the pairs list
 *
 * @returns {void}
 */
function renderPairs(pairs) {
  const ul = document.getElementById("coffee-pairs-list")
  if (!ul) return
  ul.innerHTML = ""
  pairs.forEach(function (pair) {
    const li = document.createElement("li")
    li.className = "list-group-item"
    li.textContent = pair.join(" & ")
    ul.appendChild(li)
  })
}

export { renderPairs }
